mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^roland/', include('roland.urls', namespace='roland', app_name='roland')),
    url(r'^pachangapp/', include('pachangapp.urls', namespace='pachangapp', app_name='pachangapp')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/roland/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name='roland'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/roland/'}, name='logout'),
    url(r'^newPublication/$', views.newPublication, name='newPublication'),
    url(r'^manual/$', views.manual, name='manual'),
]

mysite/roland/models.py
from django.db import models
from .constants import *
from datetime import date, datetime

# Administration and blog
class Publication(models.Model):
	title = models.CharField(max_length=MODEL_PUBLICATION_TITLE_LENGTH)
	content = models.TextField(max_length=MODEL_PUBLICATION_CONTENT_LENGTH)
	pub_date = models.DateTimeField('date published')
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	def published(self):
		return pub_date >= datetime.now()
	def __str__(self):
		return '(' + self.author.username + ') ' + self.title + '. ' + str(self.pub_date)

#Forum

# Rol definition
class Manual(models.Model):
	title = models.CharField(max_length=MODEL_MANUAL_TITLE_LENGTH)
	description = models.TextField(max_length=MODEL_MANUAL_DESCRIPTION_LENGTH)
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	def __str__(self):
		return '(' + self.author.username + ') ' + self.title
class Category(models.Model):
	name = models.CharField(max_length=MODEL_CATEGORY_NAME_LENGTH)
	content = models.TextField(max_length=MODEL_CATEGORY_CONTENT_LENGTH)
	superCategory = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
	manual  = models.ForeignKey(Manual, on_delete=models.CASCADE)
	def __str__(self):
		return self.name

mysite/roland/forms.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django import forms
from datetime import datetime
from .models import *

class PublicationForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(PublicationForm, self).__init__(*args, **kwargs)
		self.fields['title'] = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title', 'min': 3, 'max': MODEL_PUBLICATION_TITLE_LENGTH}))
		self.fields['content'] = forms.CharField(label='', widget=SummernoteWidget(attrs={'placeholder': 'Enter name'}))
		self.fields['time'] = forms.TimeField(label=' ', input_formats=['%H:%M'], widget=forms.TimeInput(attrs={'class': 'form-control', 'type':'time'}))
		self.fields['date'] = forms.DateField(label='Date', input_formats=['%Y-%m-%d'], widget=forms.TimeInput(attrs={'class': 'form-control', 'type':'date'}))
	class Meta:
		model = Publication
		fields = ('title', 'content')

mysite/roland/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from datetime import datetime
from .models import *
from .forms import *
from .constants import INDEX_PUB_PER_PAGES
def index(request):
	publications = Publication.objects.filter(pub_date__lte = datetime.now()).order_by('-pub_date')[:INDEX_PUB_PER_PAGES]
	return render(request, "roland/index.html", {'publications': publications})
def newPublication(request):
	if request.method == "POST":
		form = PublicationForm(request.POST)
		if form.is_valid():
			publication = form.save(commit=False)
			publication.author = request.user
			publication.pub_date = datetime.strptime(request.POST['date'] + ' ' + request.POST['time'], '%Y-%m-%d %H:%M')
			publication.save()
			return redirect('roland:index')
	else:
		form = PublicationForm()
	return render(request, 'roland/newPublication.html', {"form": form})
def login(request):
	if(request.user.is_authenticated):
		return redirect('roland:index')
	if request.method == 'POST':
		user = authenticate(username = request.POST['username'], password = request.POST['password'])
		if user:
			if user.is_active:
				auth_login(request, user)
				return redirect('roland:index')
		else:
			error = "User/password does not match."
			return render(request, 'roland/login.html', {'error': error})
	else:
		return render(request, 'roland/login.html', {})
@login_required(login_url=LOGIN_URL)
def manual(request):
	manual = Manual.objects.filter(title='Roland')
	if(len(manual) > 0):
		manual = manual[0]
	categories = Category.objects.filter(manual=manual, superCategory__isnull=True)
	subcategories = []
	for category in categories:
		subcategoriesRaw = list(Category.objects.filter(manual=manual, superCategory=category))
		if subcategoriesRaw:
			subcategories.append(subcategoriesRaw)
		else:
			subcategories.append(None)
	return render(request, 'roland/manual.html', {'manual': manual, 'categories': categories, 'subcategories': subcategories})

mysite/roland/templates/roland/basic_template.html
<!DOCTYPE html>
<html>
   {% load static %}
   <script src="{% static 'roland/jquery/jquery.js' %}"></script>
   <link rel="stylesheet" type="text/css" href="{% static 'roland/bootstrap/css/bootstrap.min.css' %}" />
   <script src="{% static 'roland/highcharts/highcharts.js' %}"></script>
   <script src="{% static 'roland/highcharts/highcharts-more.js' %}"></script>
   <script src="{% static 'roland/highcharts/modules/exporting.js' %}"></script>
   <script src="{% static 'roland/tether/js/tether.min.js' %}"></script>
   <script src="{% static 'roland/bootstrap/js/bootstrap.min.js' %}"></script>
   <link rel="stylesheet" href="{% static 'roland/font-awesome/css/font-awesome.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'roland/custom.css' %}" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=VT323" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Aclonica" />
   <head>
      <link rel="shortcut icon" href="{%  static 'roland/images/favicon/sword.ico' %}">
      <title>
         {% block title %}Page Title{% endblock %}
      </title>
   </head>
   {% block bodyDefinition %}
   <body>
   {% endblock %}
      <div id="banner" class="container-fluid gradient1" alt="Banner">
         <div>
            Rol Management Tool
         </div>
      </div>
      <nav class="gradient2 navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
         <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <a class="navbar-brand" href="#">Roland</a>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               {% block index %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'roland:index' %}">Home</a>
               </li>
               {% endblock %}
               {% if user.is_authenticated %}
                  {% block newPublication %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'roland:newPublication' %}">New Publication</a>
                  </li>
                  {% endblock %}
                  {% block characters %}
                  <li class="nav-item">
                     <a class="nav-link" href="#">Characters</a>
                  </li>
                  {% endblock %}
                  {% block games %}
                  <li class="nav-item">
                     <a class="nav-link" href="#">Games</a>
                  </li>
                  {% endblock %}
                  {% block Profile %}
                  <li class="nav-item">
                     <a class="nav-link" href="#">Profile</a>
                  </li>
                  {% endblock %}
                  {% block about %}
                  <li class="nav-item">
                     <a class="nav-link" href="#">About us</a>
                  </li>
                  {% endblock %}
               {% endif %}
            </ul>
            <span class="navbar-text menu-right">
               {% if user.is_authenticated %}
                  {{ user.username|title }}(<a href="{% url 'roland:logout' %}">logout</a>)
               {% else %}
                  <a class="nav-link" href="{% url 'roland:login' %}">login</a>
               {% endif %}
            </span>
         </div>
      </nav>
      {% block content-wrapper %}
         <div id="main-container" class="container">
      {% endblock %}
      {% block content %}
         Body content
      {% endblock %}
      </div>
      <div id="footer-separator">
      </div>
      <footer class="row gradient1">
         <span id="footer-inner" class="text-muted font-console font-sm">Roland, your rol management web page. By Daniel Ridao.</span>
      </footer>
      {% block javascriptFunctions %}
         <!-- Javascript functions -->
      {% endblock %}
   </body>
</html>

mysite/roland/templates/roland/basic_unlogged_template.html
<!DOCTYPE html>
<html>
   {% load static %}
   <script src="{% static 'roland/jquery/jquery.js' %}"></script>
   <link rel="stylesheet" type="text/css" href="{% static 'roland/bootstrap/css/bootstrap.min.css' %}" />
   <script src="{% static 'roland/tether/js/tether.min.js' %}"></script>
   <script src="{% static 'roland/bootstrap/js/bootstrap.min.js' %}"></script>
   <link rel="stylesheet" href="{% static 'roland/font-awesome/css/font-awesome.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'roland/custom.css' %}" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=VT323" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Aclonica" />
   <head>
      <meta charset="UTF-8">
      <title>
         {% block title %}Page Title{% endblock %}
      </title>
   </head>
   <body>
      <div id="banner" class="container-fluid gradient1" alt="Banner">
         <div>
            Rol Management Tool
         </div>
      </div>
      <nav class="gradient2 navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
         <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <a class="navbar-brand" href="#">Roland</a>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'roland:index' %}">Home</a>
               </li>
            </ul>
         </div>
      </nav>
      <div id="main-container" class="container">
      {% block content %}
         Body content
      {% endblock %}
      </div>
      <footer class="row">
         <span id="footer-inner" class="gradient1 text-muted font-console font-sm">Roland, you rol management web page. By Daniel Ridao.</span>
      </footer>
   </body>
</html>

mysite/roland/templates/roland/index.html
{% extends "roland/basic_template.html" %}
{% block title %}Roland{% endblock %}
{% block index %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'roland:index' %}">Home <span class="sr-only">(current)</span></a>
</li>
{% endblock %}
{% block content %}
  {% for publication in publications %}
  	<div class="row">
  		<div class="publication col-12">
  			<div class="row">
		  		<div class="col-12 pub_title separator-xs">
		  			<h1>{{publication.title}}</h1>
		  		</div>
		  		<div class="col-9">
		  			<h6>{{publication.author.username|title}}</h6>
		  		</div>
		  		<div class="col-3">
		  			on {{publication.pub_date}}
		  		</div>
		  		<div class="col-12 separator-sm"></div>
		  		<div class="col-12">
			  		{{publication.content|safe}}
			  	</div>
		  	</div>
	  	</div>
  	</div>
  {% endfor %}
{% endblock %}

mysite/roland/templates/roland/login.html
{% extends "roland/basic_unlogged_template.html" %}
{% block title %}Roland{% endblock %}
{% block content %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6 underlined">
  <h3>Sign in</h3>
  </div>
</div>
<div class="row separator-sm"></div>
{% if error %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ error }}</strong>
      </div>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username:</label>
          <input type="text" class="form-control" id="username" name="username" required=""/>
        </div>
        <div class="form-group">
          <label for="password">Password:</label>
          <input type="password" class="form-control" id="password" name="password" required=""/>
        </div>
        <input type="submit" class="btn btn-primary" value="Submit" />
    </form>
  </div>
</div>
{% endblock %}

mysite/roland/templates/roland/manual.html
{% extends "roland/basic_template.html" %}
{% load roland_template_tags %}
{% block title %}Roland{% endblock %}
{% block content-wrapper %}
	<div id="main-container" class="container-fluid">
{% endblock %}
{% block content %}
	<h1>{{manual.title}}</h1>
	<h5>By {{manual.author}}</h5>
	<hr/>
	{% for category in categories %}
		<h3>{{category.name}}</h3>
		{{category.content}}
		{% for subcategory in subcategories|get:forloop.counter0 %}
			<h4>{{subcategory.name}}</h4>
			{{subcategory.content}}
		{% endfor %}
	{% endfor %}
{% endblock %}

mysite/roland/templates/roland/newPublication.html
{% extends "roland/basic_template.html" %}
{% block bodyDefinition %}
   <body onload="currentDateTime()">
{% endblock %}
{% block javascriptFunctions %}
<script type="text/javascript">
function currentDateTime(){
	var datetime = new Date();
	var hours = datetime.getHours() < 10 ? '0'+datetime.getHours() : datetime.getHours()
	var minutes = datetime.getMinutes() < 10 ? '0'+datetime.getMinutes() : datetime.getMinutes()
    id_time.value = (hours + ":" + minutes);

	var dd = datetime.getDate();
	var mm = datetime.getMonth()+1; //January is 0!

	var yyyy = datetime.getFullYear();
	if(dd<10){
	    dd='0'+dd;
	} 
	if(mm<10){
	    mm='0'+mm;
	} 
	var today = yyyy+'-'+mm+'-'+dd;
	id_date.value = today;
} 
</script>
{% endblock %}
{% block title %}Roland{% endblock %}
{% block newPublication %}
	<li class="nav-item active">
		<a class="nav-link" href="{% url 'roland:newPublication' %}">New Publication <span class="sr-only">(current)</span></a>
	</li>
{% endblock %}
{% block content %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			  </button>
			  <strong>{{ error|escape }}</strong>
			</div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
       	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
		  <strong>{{ error|escape }}</strong>
		</div>
    {% endfor %}
{% endif %}
{{ form.non_field_errors }}
<form method="POST" class="row">{% csrf_token %}
	<div class="form-group col-12">
		{{ form.title.label_tag }}
		{{ form.title }}
	</div>
	<div class="form-group col-9">
		{{ form.date.label_tag }}
		{{ form.date }}
	</div>
	<div class="form-group col-3">
		<div class="form-blank-label"></div>
		{{ form.time }}
	</div>
	<div class="form-group col-12">
		{{ form.content.label_tag }}
		{{ form.media|safe }}
		{{ form.content|safe }}
	</div>
	<div class="form-group col-12">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>
{% endblock %}