mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^roland/', include('roland.urls', namespace='roland', app_name='roland')),
    url(r'^pachangapp/', include('pachangapp.urls', namespace='pachangapp', app_name='pachangapp')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/pachangapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name='pachangapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stats/(?P<usernameID>[\w.@+-]+)/$', views.stats, name='stats'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/pachangapp/'}, name='logout')
]

mysite/pachangapp/models.py
from django.db import models
from .constants import *
from datetime import date, datetime
class Group(models.Model):
	name = models.CharField(max_length=MODEL_GROUP_NAME)
	def __str__(self):
		return self.name
class City(models.Model):
	name = models.CharField(max_length=MODEL_CITY_NAME, default="")
	def __str__(self):
		return self.name
class Arena(models.Model):
	name = models.CharField(max_length=MODEL_ARENA_NAME, default="")
	city = models.ForeignKey(City, on_delete=models.CASCADE)
	def __str__(self):
		return self.name
class Stats(models.Model):
	atack = models.PositiveSmallIntegerField()
	defense = models.PositiveSmallIntegerField()
	sustain = models.PositiveSmallIntegerField()
	teamplay = models.PositiveSmallIntegerField()
	speed = models.PositiveSmallIntegerField()
	def __str__(self):
		return '(ATK:' + str(self.atack) + ', DEF:' + str(self.defense) + ', SUS:' + str(self.sustain) + ', TPL:' + str(self.teamplay) + ', SPD:' +  str(self.speed) + ')'

class User(models.Model):
	user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
	stats = models.OneToOneField(Stats, on_delete=models.CASCADE)
	known_as = models.CharField(max_length=MODEL_USER_KNOWN_AS, default="")
	groups = models.ManyToManyField(Group)
	country = models.CharField(
		max_length = 2,
        choices = MODEL_USER_COUNTRIES,
        default = 'ND'
    )
	avatar = models.ImageField(blank=True, null=True)
	def __str__(self):
		return self.user.username.title() + " " + self.known_as
class Match(models.Model):
	date = models.DateTimeField('date')
	duration = models.TimeField('duration')
	arena = models.ForeignKey(Arena, on_delete=models.CASCADE)
	team_home = models.ManyToManyField(User, related_name='home_team')
	team_visitor = models.ManyToManyField(User, related_name='visitors')
	def played(self):
		return date >= datetime.now()
	def __str__(self):
		return 'Date:' + str(self.date) + '. Duration: ' + str(self.duration) + ". "

mysite/pachangapp/forms.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django import forms
from datetime import datetime
from .models import *
from .constants import *
class UserForm(forms.ModelForm):
	def __init__(self, user, *args, **kwargs):
		if not user.country:
			default_country='ND'
		else:
			default_country=user.country
		super(UserForm, self).__init__(*args, **kwargs)
		#self.fields['avatar'] = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
		self.fields['first_name'] = forms.CharField(label='First name', initial=user.user.first_name, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First name', 'min': 3, 'max': MODEL_USER_FIRST_NAME}))
		self.fields['last_name'] = forms.CharField(label='Last name', initial=user.user.last_name, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last name', 'min': 3, 'max': MODEL_USER_LAST_NAME}))
		self.fields['known_as'] = forms.CharField(label='Known as', initial=user.known_as, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Known as', 'min': 3, 'max': MODEL_USER_KNOWN_AS}))
		self.fields['country'] = forms.ChoiceField(choices=MODEL_USER_COUNTRIES, initial=default_country, label='Country', widget=forms.Select(attrs={'class': 'form-control'}))
		self.fields['avatar'] = forms.ImageField(label='Avatar', initial=user.avatar)
	class Meta:
		model = User
		fields = ('avatar', 'known_as', 'country')
class StatsForm(forms.ModelForm):
	def __init__(self, user, choices, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)
	class Meta:
		fields = ('user',)

mysite/pachangapp/views.py
from PIL import Image
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from django.db.models import Q
from datetime import datetime
from .models import *
from .forms import *
from .constants import LOGIN_URL
from .utils import removeFiles
import re
import os
@login_required(login_url = LOGIN_URL)
def index(request):
	user = User.objects.filter(user=request.user).first()
	matches = Match.objects.filter(Q(team_home=user) | Q(team_visitor=user)).distinct()[:5]
	return render(request, "pachangapp/index.html", {'matches': matches})
@login_required(login_url = LOGIN_URL)
def stats(request, usernameID=False):
	if(not usernameID):
		query = request.user.username
	else:
		query = usernameID
	user = User.objects.filter(user__username=query).first()
	return render(request, "pachangapp/stats.html", {'profUser': user})
@login_required(login_url = LOGIN_URL)
def profile(request):
	user = User.objects.filter(user=request.user).first()
	if request.method == 'POST':
		form = UserForm(user, request.POST, request.FILES)
		if form.is_valid():
			''' We check that we have an avatar, if so we will update the avatar in the user '''
			if request.FILES and request.FILES['avatar']:
				myfile = request.FILES['avatar']
				print(myfile)
				fs = FileSystemStorage()
				path = os.path.join(MODEL_USER_AVATAR, request.user.username)
				#For security we will remove all the avatar in the directory to not overload the server
				removeFiles(os.path.join(settings.MEDIA_ROOT, path))
				path = os.path.join(path, 'avatar' + myfile.name[-4:])
				filename = fs.save(path, myfile)
				
				image = Image.open(os.path.join(settings.MEDIA_ROOT, path))
				image.thumbnail(MODEL_USER_IMAGE_SIZE, Image.ANTIALIAS)
				image.save(os.path.join(settings.MEDIA_ROOT, path))
				user.avatar = path
			request.user.first_name = request.POST['first_name']
			request.user.last_name = request.POST['last_name']
			request.user.save()
			user.known_as = request.POST['known_as']
			user.country = request.POST['country']
			user.save()
			return redirect('pachangapp:profile')
	else:
		form = UserForm(user)
	return render(request, 'pachangapp/profile.html', {"form": form, 'profUser': user})
def login(request):
	if(request.user.is_authenticated):
		return redirect('pachangapp:index')
	if request.method == 'POST':
		user = authenticate(username = request.POST['username'], password = request.POST['password'])
		if user:
			if user.is_active:
				auth_login(request, user)
				return redirect('pachangapp:index')
		else:
			error = "User/password does not match."
			return render(request, 'pachangapp/login.html', {'error': error})
	else:
		return render(request, 'pachangapp/login.html', {})

mysite/pachangapp/templates/pachangapp/basic_template.html
<html>
   {% load static %}
   <script src="{% static 'pachangapp/jquery/jquery.js' %}"></script>
   <link rel="stylesheet" type="text/css" href="{% static 'pachangapp/bootstrap/css/bootstrap.min.css' %}" />
   <script src="{% static 'pachangapp/highcharts/highcharts.js' %}"></script>
   <script src="{% static 'pachangapp/highcharts/highcharts-more.js' %}"></script>
   <script src="{% static 'pachangapp/highcharts/modules/exporting.js' %}"></script>
   <script src="{% static 'pachangapp/highcharts/themes/dark-unica.js' %}"></script>
   <script src="{% static 'pachangapp/tether/js/tether.min.js' %}"></script>
   <script src="{% static 'pachangapp/bootstrap/js/bootstrap.min.js' %}"></script>
   <link rel="stylesheet" href="{% static 'pachangapp/font-awesome/css/font-awesome.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'pachangapp/custom.css' %}" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=VT323" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Aclonica" />
   <head>
      <link rel="shortcut icon" href="{%  static 'pachangapp/images/favicon/football.ico' %}">
      <title>
         {% block title %}Page Title{% endblock %}
      </title>
   </head>
   {% block bodyDefinition %}
   <body>
   {% endblock %}
      <div id="banner" class="container-fluid gradient1" alt="Banner">
         <div class="row">
            <div class="col-10">
               PachangAPP
            </div>
            <!-- <div id="logo" class="col-2"></div> -->
         </div>
      </div>
      <nav class="gradient2 navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
         <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <a class="navbar-brand" href="#">PachangAPP</a>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               {% block index %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'pachangapp:index' %}">Home</a>
               </li>
               {% endblock %}
               {% if user.is_authenticated %}
                  {% block profile %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'pachangapp:profile' %}">Profile</a>
                  </li>
                  {% endblock %}
                  {% block stats %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'pachangapp:stats' %}">Stats</a>
                  </li>
                  {% endblock %}
               {% endif %}
            </ul>
            <span class="navbar-text menu-right">
               {% if user.is_authenticated %}
                  {{ user.username|title }}(<a href="{% url 'pachangapp:logout' %}">logout</a>)
               {% else %}
                  <a class="nav-link" href="{% url 'pachangapp:login' %}">login</a>
               {% endif %}
            </span>
         </div>
      </nav>
      <div id="main-container" class="container">
      {% block content %}
         Body content
      {% endblock %}
      </div>
      <div id="footer-separator">
      </div>
      <footer class="row gradient3">
         <span id="footer-inner" class="text-muted font-console font-sm">PachangAPP, for you noobs that think you are good at playing football, you are not. By Daniel Ridao.</span>
      </footer>
      {% block javascriptFunctions %}
         <!-- Javascript functions -->
      {% endblock %}
   </body>
</html>

mysite/pachangapp/templates/pachangapp/basic_unlogged_template.html
<html>
   {% load static %}
   <script src="{% static 'pachangapp/jquery/jquery.js' %}"></script>
   <link rel="stylesheet" type="text/css" href="{% static 'pachangapp/bootstrap/css/bootstrap.min.css' %}" />
   <script src="{% static 'pachangapp/tether/js/tether.min.js' %}"></script>
   <script src="{% static 'pachangapp/bootstrap/js/bootstrap.min.js' %}"></script>
   <link rel="stylesheet" href="{% static 'pachangapp/font-awesome/css/font-awesome.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'pachangapp/custom.css' %}" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=VT323" />
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Aclonica" />
   <head>
      <link rel="shortcut icon" href="{%  static 'pachangapp/images/favicon/football.ico' %}">
      <title>
         {% block title %}Page Title{% endblock %}
      </title>
   </head>
   <body>
      <div id="banner" class="container-fluid gradient1" alt="Banner">
         <div>
            PachangAPP
         </div>
      </div>
      <nav class="gradient2 navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
         <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <a class="navbar-brand" href="#">PachangAPP</a>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'pachangapp:index' %}">Home</a>
               </li>
            </ul>
         </div>
      </nav>
      <div id="main-container" class="container">
      {% block content %}
         Body content
      {% endblock %}
      </div>
      <footer class="row gradient3">
         <span id="footer-inner" class="text-muted font-console font-sm">PachangAPP, for you noobs that think you are good at playing football, you are not. By Daniel Ridao.</span>
      </footer>
   </body>
</html>

mysite/pachangapp/templates/pachangapp/index.html
{% extends "pachangapp/basic_template.html" %}
{% load pachangapp_template_tags %}
{% block title %}PachangAPP{% endblock %}
{% block index %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'pachangapp:index' %}">Home <span class="sr-only">(current)</span></a>
</li>
{% endblock %}
{% block content %}
	{% if not matches %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<strong>Hey there!</strong> It seems that there isn't any match played yet.
		</div>
	{% endif %}
	{% for match in matches %}
		<div class="row">
			<div class="col-6">
				<h3>Home</h3>
			</div>
			<div class="col-6">
				<h3>Visitors</h3>
			</div>
		</div>
		<div class="row">
			<div class="col-6">
				<table class="table table-striped">
				  <thead class="thead-inverse">
				    <tr>
				      <th>#</th>
				      <th>Username</th>
				      <th>Known as</th>
				    </tr>
				  </thead>
				  <tbody class="color-green">
				  	{% for player in match.team_home|all %}
				    <tr>
				      <th scope="row">{{forloop.counter}}</th>
				      <td><a href="{% url 'pachangapp:stats' player.user.username %}">{{player.user.username|title}}</a></td>
				      <td>{{player.known_as|title}}</td>
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
			<div class="col-6">
				<table class="table table-striped">
				  <thead class="thead-inverse">
				    <tr>
				      <th>#</th>
				      <th>Username</th>
				      <th>Known as</th>
				    </tr>
				  </thead>
				  <tbody class="color-green">
				  	{% for player in match.team_visitor|all %}
				    <tr>
				      <th scope="row">{{forloop.counter}}</th>
				      <td><a href="{% url 'pachangapp:stats' player.user.username %}">{{player.user.username|title}}</a></td>
				      <td>{{player.known_as|title}}</td>
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-3">
				<h5>Date: {{match.date}}</h5>
			</div>
			<div class="col-3">
				<h5>Duration: {{match.duration}}</h5>
			</div>
			<div class="col-6">
				<h5>Place: {{match.arena|title}} Arena</h5>
			</div>
		</div>
		<div class="col-12 color-green separator-xs"></div>
		<div class="col-12 underlined color-green separator-sm"></div>
	{% endfor %}
{% endblock %}

mysite/pachangapp/templates/pachangapp/login.html
{% extends "pachangapp/basic_unlogged_template.html" %}
{% block title %}PachangAPP{% endblock %}
{% block content %}
<div class="row separator-sm"></div>
{% if error %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ error }}</strong>
      </div>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="col-12 underlined color-green">
      <h3>Sign in</h3>
    </div>
    <div class="col-12">
      <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" required=""/>
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" required=""/>
          </div>
          <input type="submit" class="btn btn-primary btn-green" value="Submit" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

mysite/pachangapp/templates/pachangapp/profile.html
{% extends "pachangapp/basic_template.html" %}
{% load pachangapp_template_tags %}
{% block title %}PachangAPP{% endblock %}
{% block profile %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'pachangapp:profile' %}">Profile <span class="sr-only">(current)</span></a>
</li>
{% endblock %}


{% block content %}
	{% if profUser.avatar %}
		<img src="{{ profUser.avatar.url }}"/>
	{% endif %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary btn-green">Submit</button>
	</form>
{% endblock %}

mysite/pachangapp/templates/pachangapp/stats.html
{% extends "pachangapp/basic_template.html" %}
{% load pachangapp_template_tags %}
{% block title %}PachangAPP{% endblock %}
{% block stats %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'pachangapp:stats' %}">Stats <span class="sr-only">(current)</span></a>
</li>
{% endblock %}
{% block content %}
<audio autoplay="" controls="" preload="auto" loop="true" autobuffer>
    <source src="/static/pachangapp/sounds/Fatboy-Slim-Funk-Soul-Brother.mp3" type="audio/mpeg">
</audio>
<div class="row"></div>
<div class="row">
	<div class="col-2"></div>
	<div class="col-4">
		<img class="profile-image" src="{{profUser.avatar.url}}"/>
	</div>
	<div class="col-4">
		<div class="row">User: {{profUser.user.username|title}}</div>
		<div class="row">Name: {{profUser.user.first_name}}</div>
		<div class="row">Surname: {{profUser.user.last_name}}</div>
		<div class="row">Known as: {{profUser.known_as}}</div>
	</div>
	<div class="col-2"></div>
</div>
<div class="row">
	<div class="col-2"></div>
	<div class="col-8"><div id="container"></div></div>
</div>
<script>
	Highcharts.chart('container', {

    chart: {
        polar: true,
        type: 'line'
    },

    title: {
        text: 'Player Stats',
        x: -80
    },

    pane: {
        size: '80%'
    },

    xAxis: {
        categories: ['Atack', 'Defense', 'Sustain', 'Teamplay', 'Speed'],
        tickmarkPlacement: 'on',
        lineWidth: 0
    },

    yAxis: {
        gridLineInterpolation: 'polygon',
        lineWidth: 0,
        min: 0,
        max: 10
    },

    tooltip: {
        shared: true,
        pointFormat: '<span style="color:{series.color}">{series.name}: <b>{point.y:,.0f}/10</b><br/>'
    },

    legend: {
        align: 'right',
        verticalAlign: 'top',
        y: 70,
        layout: 'vertical'
    },

    series: [{
        name: '{{profUser.user.username}}',
        data: [{{profUser.stats.atack}}, {{profUser.stats.defense}}, {{profUser.stats.sustain}}, {{profUser.stats.teamplay}}, {{profUser.stats.speed}}],
        pointPlacement: 'on'
    }]

});
</script>
{% endblock %}